### ISSUE TITLE
refresh! fails if no alg key is supplied

### ISSUE THREAD

**Issue by hhaensel** [tanmaykm/JWTs.jl#18]
Currently `refresh!()` fails if a key does not contain an "alg" key.

According to the JWK specification https://www.rfc-editor.org/rfc/rfc7517.html#section-4.4 the alg key is optional, e.g.if only one algorithm is supported.

This is currently the case for Microsoft Azure AD. Therefore, OpenIDConnect fails to validate a token.

I propose to allow for a default_alg value which is taken when no alg key is provided by the key provider. As "RS256" is the default algorithm for OIDC, I'd propose to default `default_alg` to this value.

That way, OpenIDConnect.jl would work out of the box for Azure AD.

I've submitted a corresponding PR #17 .

**Comment by tanmaykm** [comment]
Fixed via #17
