### ISSUE TITLE
How to extract modulus "n" and exponent "e" from public key

### ISSUE THREAD

**Issue by schlichtanders** [tanmaykm/JWTs.jl#21]
is there a simple way using Julia to extract the modulus and exponent from a given public key?

these seem to be needed to create the jwts public keys in the first place

**Comment by tanmaykm** [comment]
You can find an example to do that using openssl in [`test/keys/rsa/genkey.sh`](https://github.com/tanmaykm/JWTs.jl/blob/dece86f6a9f74258c7c5b463e8f71992cefa6ebc/test/keys/rsa/genkey.sh)
