### ISSUE TITLE
Specify algorithm when validating token?

### ISSUE THREAD

**Issue by ahjulstad** [tanmaykm/JWTs.jl#28]
Other libraries  ([pyjwt](https://pyjwt.readthedocs.io/en/latest/) ) require the specification of expected algorithms when validating the token. 

```
decoded = jwt.decode(encoded, public_key, algorithms=["RS256"])
```

Would something similar make sense here?

**Comment by tanmaykm** [comment]
Yes... I think it will be good to have an optional argument in `validate!` for that.

The `validate!` method requires an explicit key to be specified. The `validate!` method where only a key set is supplied to `validate!` uses the key id specified in the JWT to validate and also ensures that the algorithm specified in the JWT matches that of the key. We could additionally ensure it matches the one explicitly passed in the optional argument.

We should also document the `alg` method that returns the key or JWT algorithm.
